name: Workflow Inicial Demo Caixa

on: 
  workflow_dispatch:

jobs:
  greet:
    env:
      MY_ENV: "ARTHUR"
    runs-on: ubuntu-latest
    steps:
      - name: saudacao ao usuario
        run: echo "Alo mundo"
      - run: ls -l
      - uses: actions/checkout@v6
      - run: ls -l
      - name: execucao de um script multi-linha
        run: |
            echo: "olá $MY_ENV"
            echo: "Olá, $GITHUB_ACTOR"



